### PR TITLE
For updating Spring Boot version

### PR DESCRIPTION
**Pull request by vimal-java-dev**
Issue: [Update Spring Boot version #5](https://github.com/spring-guides/gs-spring-cloud-task/issues/5#issuecomment-1740034009)

- Both pom.xml files have been updated manually with typing, It is not updated via run the project in any IDE.(Please simplify this)
- But how to run the project, should I convert it into a Maven project? or there is another way to run it?
- Because without running the application from IDE as Spring tool suite 
- Below Action will not be performed.
```
use task;
show tables; --show all tables that Spring Cloud Task created
select * from task_execution;
```

### CODE REVIEW

**Comment by robertmcnees** [comment]
Thanks for the PR!

Can you exclude the `application.properties` from this PR?  I'd like to leave it commented out so that Docker is not required in the base case and [this line](https://github.com/spring-guides/gs-spring-cloud-task/blob/ae3cf68f7f2620b53fb1b5cb71f041989e9782b1/README.adoc?plain=1#L39) remains true.

**Comment by vimal-java-dev** [comment]
**Project has looked as multiple module as pom.xml.**

- So tell me, Do i need to run as converting in maven with parent pom.xml?
- If it would be to mention the 2 child module pom.xml of complete and initial entry into parent pom.xml.

**Comment by vimal-java-dev** [comment]
Does the project need to be run with Maven for the updating Spring boot version?

- If it must be, Then It is a 2-module project with respective to 2 pom.xml as complete and initial.
- And there is no parent pom.xml for mentioning the entry of those two modules,
- So, Should I need to create a parent pom.xml?
---
- And last https://github.com/spring-guides/gs-spring-cloud-task/pull/6#issuecomment-1740619073
- There is no Docker needed to run the application
- Therefore how to run h2 DB without username and password and URL entry in property file.
- --

**Comment by robertmcnees** [comment]
Hi @vimalJD .  Thanks for the PR!  Looks good.

Regarding the project structure, the `initial` and `complete` folders are intended to be separate projects.  There is no need for a parent `pom.xml` in this case.

You are correct that MariaDB, changes in `application.properties`, and Docker are required to perform the last step of the guide.  However the guide can also build with H2 for the fastest getting started experience.  This can work without any datasource defined.

> Spring Cloud Task using In Memory H2
> For the first step, we use Spring Cloud Task with an embedded H2 datastore. If no spring.datasource properties are detected on project initialization, Spring Cloud Task spins up a new H2 instance to store the executed task results. This happens without any extra configuration. This facilitates a quick way to get up and running, but the results of your executed task are lost when the application completes and the H2 database shuts down. For this step in the guide, ensure that the spring.datasource properties in application.properites are commented out.

**Comment by vimal-java-dev** [comment]
**Glad to connect with you,** **Having learned** from this open source contribution with my favourite programming language as a **java using spring boot** for merging my pull request. Meanwhile, learnt how **docker** could communicate with database using tools such as **git bash** command as well as **WSL2** with **_linux distros - Ubuntu._** and again thanks for [this ](https://github.com/spring-guides/gs-spring-cloud-task/pull/6#issuecomment-1742156905) explaination.

**Pull request merged**
